/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as ChangesRouteImport } from './routes/changes'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiReportRouteImport } from './routes/api/report'
import { Route as ApiSkyWindowRouteImport } from './routes/api/sky-window'
import { Route as ApiSkyYearRouteImport } from './routes/api/sky-year'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangesRoute = ChangesRouteImport.update({
  id: '/changes',
  path: '/changes',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportRoute = ApiReportRouteImport.update({
  id: '/api/report',
  path: '/api/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSkyWindowRoute = ApiSkyWindowRouteImport.update({
  id: '/api/sky-window',
  path: '/api/sky-window',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSkyYearRoute = ApiSkyYearRouteImport.update({
  id: '/api/sky-year',
  path: '/api/sky-year',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/accessibility': typeof AccessibilityRoute
  '/changes': typeof ChangesRoute
  '/credits': typeof CreditsRoute
  '/guide': typeof GuideRoute
  '/legal': typeof LegalRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/report': typeof ApiReportRoute
  '/api/sky-window': typeof ApiSkyWindowRoute
  '/api/sky-year': typeof ApiSkyYearRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/accessibility': typeof AccessibilityRoute
  '/changes': typeof ChangesRoute
  '/credits': typeof CreditsRoute
  '/guide': typeof GuideRoute
  '/legal': typeof LegalRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/report': typeof ApiReportRoute
  '/api/sky-window': typeof ApiSkyWindowRoute
  '/api/sky-year': typeof ApiSkyYearRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/accessibility': typeof AccessibilityRoute
  '/changes': typeof ChangesRoute
  '/credits': typeof CreditsRoute
  '/guide': typeof GuideRoute
  '/legal': typeof LegalRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/report': typeof ApiReportRoute
  '/api/sky-window': typeof ApiSkyWindowRoute
  '/api/sky-year': typeof ApiSkyYearRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/accessibility'
    | '/changes'
    | '/credits'
    | '/guide'
    | '/legal'
    | '/privacy'
    | '/settings'
    | '/terms'
    | '/api/health'
    | '/api/report'
    | '/api/sky-window'
    | '/api/sky-year'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/accessibility'
    | '/changes'
    | '/credits'
    | '/guide'
    | '/legal'
    | '/privacy'
    | '/settings'
    | '/terms'
    | '/api/health'
    | '/api/report'
    | '/api/sky-window'
    | '/api/sky-year'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/accessibility'
    | '/changes'
    | '/credits'
    | '/guide'
    | '/legal'
    | '/privacy'
    | '/settings'
    | '/terms'
    | '/api/health'
    | '/api/report'
    | '/api/sky-window'
    | '/api/sky-year'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AccessibilityRoute: typeof AccessibilityRoute
  ChangesRoute: typeof ChangesRoute
  CreditsRoute: typeof CreditsRoute
  GuideRoute: typeof GuideRoute
  LegalRoute: typeof LegalRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiReportRoute: typeof ApiReportRoute
  ApiSkyWindowRoute: typeof ApiSkyWindowRoute
  ApiSkyYearRoute: typeof ApiSkyYearRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changes': {
      id: '/changes'
      path: '/changes'
      fullPath: '/changes'
      preLoaderRoute: typeof ChangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/report': {
      id: '/api/report'
      path: '/api/report'
      fullPath: '/api/report'
      preLoaderRoute: typeof ApiReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sky-window': {
      id: '/api/sky-window'
      path: '/api/sky-window'
      fullPath: '/api/sky-window'
      preLoaderRoute: typeof ApiSkyWindowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sky-year': {
      id: '/api/sky-year'
      path: '/api/sky-year'
      fullPath: '/api/sky-year'
      preLoaderRoute: typeof ApiSkyYearRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AccessibilityRoute: AccessibilityRoute,
  ChangesRoute: ChangesRoute,
  CreditsRoute: CreditsRoute,
  GuideRoute: GuideRoute,
  LegalRoute: LegalRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiReportRoute: ApiReportRoute,
  ApiSkyWindowRoute: ApiSkyWindowRoute,
  ApiSkyYearRoute: ApiSkyYearRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
